@SignalRWebHub_HostAddress = http://localhost:5036

GET {{SignalRWebHub_HostAddress}}/weatherforecast/
Accept: application/json

###


###  OWNERS  NEW VIEWED AND DONE MESSAGES
###
POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "NOTVIEWED",
    "messageVisible": true,
    "messageTitle": "Owner_New-Message-NOTVIEWED-NOTDONE", 
    "content": "This is a new message  sent to the owner ", 
    "sender": "Admin@massload.com", 
    "MessageOwnerStatus": "NOTDONE",
    "targetRecipient":"softwareeng@massload.com"
}



###
POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "VIEWED",
    "messageVisible": true,
    "messageTitle": "Owner_VIEWED-NOTDONE", 
    "content": "This is a View message ", 
    "sender": "Admin@massload.com", 
     "MessageOwnerStatus": "NOTDONE",
    "targetRecipient":"softwareeng@massload.com"
}

###

POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "VIEWED",
    "messageVisible": true,
    "messageTitle": "Owner_VIEWED-DONE", 
    "content": "This is a done message", 
    "MessageOwnerStatus": "DONE",
    "sender": "Admin@massload.com", 
    "targetRecipient":"softwareeng@massload.com"
 
}
###

POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "NOTVIEWED",
    "messageVisible": true,
    "messageTitle": "Owner_NOTVIEWED-DONE", 
    "content": "This is a done message", 
    "MessageOwnerStatus": "DONE",
    "sender": "Admin@massload.com", 
    "targetRecipient":"softwareeng@massload.com"
 
}

###  PARTICIPANT HIGH PRIORITIES NEW VIEWED AND DONE MESSAGES
###
POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "NOTVIEWED",
    "messageVisible": true,
    "messageTitle": "Participant_NOTVIEWED/NOTDONE", 
    "content": "This is a new message with a high priority sent to the owner, you can acknowledge viewing  ,archive and reply using the icons below", 
    "sender": "Admin@massload.com", 
     "MessageOwnerStatus": "NOTDONE",
    "targetRecipient":"assembler@massload.com"

}



###
POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "VIEWED",
    "messageVisible": true,
    "messageTitle": "Participant_VIEWED/NOTDONE", 
    "content": "This is a View message with a high priority sent to  assembler@massload.com but can been seen as a participant", 
    "sender": "Admin@massload.com", 
     "MessageOwnerStatus": "NOTDONE",
    "targetRecipient":"assembler@massload.com"
}

###

POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "NOTVIEWED",
    "messageVisible": true,
    "messageTitle": "Participant_NOTVIEWED/DONE", 
    "content": "This is a View message with a high priority sent to to  assembler@massload.com but  participant receives a copy", 
     "MessageOwnerStatus": "DONE",
    "sender": "Admin@massload.com", 

    "targetRecipient":"assembler@massload.com"

}

###
###
### PARTICIPANTS LOW PRIORITIES NEW VIEWED AND DONE MESSAGES
POST {{SignalRWebHub_HostAddress}}/weatherforecast/
Content-Type: application/json

{
    "RoomName": "Enginnering_Room",
    "messageStatus": "VIEWED",
    "messageVisible": true,
    "messageTitle": "Participant_VIEWED/DONE", 
  "content": "This is a new message with a low priority sent to   assembler@massload.com but received as a participant, you can acknowledge viewing  ,archive and reply using the icons below", 
    "sender": "Admin@massload.com", 
     "MessageOwnerStatus": "DONE",
    "targetRecipient":"assembler@massload.com"

}

